import { Pet } from './petStore'

const SPECIES_PERSONALITY: Record<string, Record<string, number>> = {
  fox: { braveness: 5, curiosity: 9, kindness: 6, independence: 7, playfulness: 8, wisdom: 7 },
  dragon: { braveness: 8, curiosity: 6, kindness: 7, independence: 9, playfulness: 3, wisdom: 9 },
  phoenix: { braveness: 7, curiosity: 5, kindness: 6, independence: 8, playfulness: 7, wisdom: 8 },
  turtle: { braveness: 4, curiosity: 4, kindness: 8, independence: 6, playfulness: 3, wisdom: 9 },
  tiger: { braveness: 9, curiosity: 6, kindness: 5, independence: 8, playfulness: 7, wisdom: 5 },
  qilin: { braveness: 6, curiosity: 5, kindness: 9, independence: 7, playfulness: 4, wisdom: 8 },
}

const DEFAULT_PETS: Pet[] = [
  {
    id: 'char_2d2ca06b',
    user_id: 'demo-user',
    name: '哈基咪',
    species: 'cat',
    personality: { braveness: 4, curiosity: 10, kindness: 8, independence: 6, playfulness: 9, wisdom: 5 },
    mood: 90,
    energy: 80,
    spiritual_power: 30,
    cultivation_level: 1,
    current_region: 'qingqiu',
    inventory: [],
    health: 100,
    status: 'normal',
    controller_type: 'player',
    controller_version: 1,
    x: 5,
    y: 5,
    last_active: new Date().toISOString(),
    last_player_heartbeat: new Date().toISOString(),
    affinity_map: {},
    goals: [],
  },
  {
    id: 'pet-fox-001',
    user_id: 'demo-user',
    name: '灵狐',
    species: 'fox',
    personality: SPECIES_PERSONALITY.fox,
    mood: 85,
    energy: 90,
    spiritual_power: 50,
    cultivation_level: 1,
    current_region: 'qingqiu',
    inventory: [],
    health: 100,
    status: 'normal',
    controller_type: 'agent',
    controller_version: 1,
    x: 15,
    y: 15,
    last_active: new Date().toISOString(),
    last_player_heartbeat: null,
    affinity_map: {},
    goals: [],
  },
  {
    id: 'pet-dragon-001',
    user_id: 'demo-user',
    name: '苍龙',
    species: 'dragon',
    personality: SPECIES_PERSONALITY.dragon,
    mood: 75,
    energy: 80,
    spiritual_power: 80,
    cultivation_level: 3,
    current_region: 'kunlun',
    inventory: [],
    health: 100,
    status: 'normal',
    controller_type: 'agent',
    controller_version: 1,
    x: 30,
    y: 10,
    last_active: new Date().toISOString(),
    last_player_heartbeat: null,
    affinity_map: {},
    goals: [],
  },
  {
    id: 'pet-phoenix-001',
    user_id: 'demo-user',
    name: '朱雀',
    species: 'phoenix',
    personality: SPECIES_PERSONALITY.phoenix,
    mood: 90,
    energy: 85,
    spiritual_power: 70,
    cultivation_level: 2,
    current_region: 'xinghai',
    inventory: [],
    health: 100,
    status: 'normal',
    controller_type: 'agent',
    controller_version: 1,
    x: 35,
    y: 25,
    last_active: new Date().toISOString(),
    last_player_heartbeat: null,
    affinity_map: {},
    goals: [],
  },
  {
    id: 'pet-turtle-001',
    user_id: 'demo-user',
    name: '玄武',
    species: 'turtle',
    personality: SPECIES_PERSONALITY.turtle,
    mood: 60,
    energy: 95,
    spiritual_power: 60,
    cultivation_level: 2,
    current_region: 'donghai',
    inventory: [],
    health: 100,
    status: 'normal',
    controller_type: 'agent',
    controller_version: 1,
    x: 10,
    y: 30,
    last_active: new Date().toISOString(),
    last_player_heartbeat: null,
    affinity_map: {},
    goals: [],
  },
  {
    id: 'pet-tiger-001',
    user_id: 'demo-user',
    name: '白虎',
    species: 'tiger',
    personality: SPECIES_PERSONALITY.tiger,
    mood: 70,
    energy: 85,
    spiritual_power: 75,
    cultivation_level: 3,
    current_region: 'lingxu',
    inventory: [],
    health: 85,
    status: 'normal',
    controller_type: 'agent',
    controller_version: 1,
    x: 25,
    y: 35,
    last_active: new Date().toISOString(),
    last_player_heartbeat: null,
    affinity_map: {},
    goals: [],
  },
  {
    id: 'pet-qilin-001',
    user_id: 'demo-user',
    name: '麒麟',
    species: 'qilin',
    personality: SPECIES_PERSONALITY.qilin,
    mood: 95,
    energy: 75,
    spiritual_power: 90,
    cultivation_level: 4,
    current_region: 'xinghai',
    inventory: [],
    health: 100,
    status: 'normal',
    controller_type: 'agent',
    controller_version: 1,
    x: 40,
    y: 20,
    last_active: new Date().toISOString(),
    last_player_heartbeat: null,
    affinity_map: {},
    goals: [],
  },
]

export function getMockPets(): Pet[] {
  return DEFAULT_PETS
}

export function createMockPet(data: { name: string; species: string; personality?: string }): Pet {
  const id = `pet-${data.species}-${Date.now()}`
  const personality = SPECIES_PERSONALITY[data.species] || SPECIES_PERSONALITY.fox
  
  return {
    id,
    user_id: 'demo-user',
    name: data.name,
    species: data.species,
    personality,
    mood: 80,
    energy: 100,
    spiritual_power: 30,
    cultivation_level: 1,
    current_region: 'qingqiu',
    inventory: [],
    health: 100,
    status: 'normal',
    controller_type: 'agent',
    controller_version: 1,
    x: Math.random() * 30 + 10,
    y: Math.random() * 30 + 10,
    last_active: new Date().toISOString(),
    last_player_heartbeat: null,
    affinity_map: {},
    goals: [],
  }
}

export function getMockCharacterStatus(charId: string) {
  const pet = DEFAULT_PETS.find(p => p.id === charId)
  if (!pet) {
    return null
  }
  return {
    ...pet,
    position_x: Math.random() * 100 + 50,
    position_y: Math.random() * 100 + 50,
  }
}